# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
target 'ShiRongXinMarketMallProject' do
  inhibit_all_warnings! #屏蔽所有warning
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShiRongXinMarketMallProject
  pod 'MJRefresh'
  pod 'AFNetworking'
  pod 'SVProgressHUD'
  pod 'Masonry'
  pod 'MJExtension'
  pod 'SDWebImage'
  pod 'SDCycleScrollView'
  pod 'BRPickerView'#时间选择器
  pod 'Bugly'#异常上传
  pod 'MBProgressHUD'
  pod 'Reachability'
  pod 'ReactiveObjC'
  pod 'YYKit'
  pod 'IQKeyboardManager'
  pod 'TZImagePickerController'
  pod 'M80AttributedLabel'
  pod 'Toast'
  pod 'LXMButtonImagePosition', '~> 1.2.0'#按钮文字位置
  pod 'RollingNotice'#文字滚动
  pod 'JXPagingView/Pager'
  pod 'JXCategoryView'
  pod 'WechatOpenSDK'
  pod 'AlipaySDK-iOS', '~> 15.8.11'#  pod 'AlipaySDK-iOS'#支付宝支付
  pod 'UMCShare/Social/ReducedWeChat'
  pod 'HSUpdateApp'
  pod 'JPush'
  pod 'ZKCycleScrollView'  # 轮播图，网络图片加载
  pod 'GKPhotoBrowser'
  pod 'WMZBanner'
  pod 'Meiqia'  #美洽 SDK
  pod 'SocketRocket'
#  pod 'Reveal-SDK', :configurations => ['Debug'] #调试使用
  pod 'LookinServer', :configurations => ['Debug']
  target 'ShiRongXinMarketMallProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShiRongXinMarketMallProjectUITests' do
    # Pods for testing
  end

end
